# Generated by Django 4.1.7 on 2023-04-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductGallery',
        ),
    ]
